[package]
name = "option_bastion"
description = "Smart Contract keeping track of options to be added to Carmine Options AMM"
version = "0.1.0"
cairo-version = "2.3.1"

[dependencies]
cubit = { git = "https://github.com/influenceth/cubit.git", commit = "b4590530d5aeae9aabd36740cc2a3d9e6adc5fde" }
starknet = ">=2.3.0"

[[target.starknet-contract]]
